/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/academics/classes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["list_4"];
        readonly put?: never;
        readonly post: operations["create_4"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/academics/classes/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: operations["update_5"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/academics/classes/{id}/sections": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["addSection"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/academics/classes/order": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: operations["reorder"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/academics/sections/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: operations["updateSection"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/academics/sessions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["list_3"];
        readonly put?: never;
        readonly post: operations["create_3"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/academics/sessions/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: operations["update_4"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/academics/sessions/{id}/current": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["makeCurrent"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/access/permissions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["permissions"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/access/roles": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["roles"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/access/users": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["users"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/audit": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["search"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["login"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["logout"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/password": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["changePassword"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/guardians": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["list_2"];
        readonly put?: never;
        readonly post: operations["create_2"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/guardians/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: operations["update_3"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/guardians/{id}/students": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["students"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["me"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/school/profile": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["profile"];
        readonly put: operations["update_2"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/schools": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["list_1"];
        readonly put?: never;
        readonly post: operations["create_1"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/schools/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/students": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["list"];
        readonly put?: never;
        readonly post: operations["create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/students/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["find"];
        readonly put: operations["update_1"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/students/{id}/enrolments": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["enrol"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/students/{id}/enrolments/{enrolmentId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: operations["updateEnrolment"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/students/{studentId}/guardians": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["link"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/students/{studentId}/guardians/{linkId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: operations["update"];
        readonly post?: never;
        readonly delete: operations["unlink"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/students/import": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["importStudents"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/students/import/validate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["validate"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly AcademicSessionResponse: {
            readonly current: boolean;
            /** Format: date */
            readonly endsOn: string;
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: date */
            readonly startsOn: string;
        };
        readonly ApiError: {
            readonly code: string;
            readonly details?: {
                readonly [key: string]: string;
            };
            readonly message: string;
        };
        readonly ApiResponseAcademicSessionResponse: {
            readonly data?: components["schemas"]["AcademicSessionResponse"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseEnrolment: {
            readonly data?: components["schemas"]["Enrolment"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseGuardianSummary: {
            readonly data?: components["schemas"]["GuardianSummary"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseImportReport: {
            readonly data?: components["schemas"]["ImportReport"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseListAcademicSessionResponse: {
            readonly data?: readonly components["schemas"]["AcademicSessionResponse"][];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseListGuardianStudent: {
            readonly data?: readonly components["schemas"]["GuardianStudent"][];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseListPermissionDefinition: {
            readonly data?: readonly components["schemas"]["PermissionDefinition"][];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseListRoleResponse: {
            readonly data?: readonly components["schemas"]["RoleResponse"][];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseListSchoolClassResponse: {
            readonly data?: readonly components["schemas"]["SchoolClassResponse"][];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseListSchoolResponse: {
            readonly data?: readonly components["schemas"]["SchoolResponse"][];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseListUserSummary: {
            readonly data?: readonly components["schemas"]["UserSummary"][];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseLoginResponse: {
            readonly data?: components["schemas"]["LoginResponse"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseMeResponse: {
            readonly data?: components["schemas"]["MeResponse"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponsePageResponseAuditEventResponse: {
            readonly data?: components["schemas"]["PageResponseAuditEventResponse"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponsePageResponseGuardianSummary: {
            readonly data?: components["schemas"]["PageResponseGuardianSummary"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponsePageResponseStudentSummary: {
            readonly data?: components["schemas"]["PageResponseStudentSummary"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseSchoolClassResponse: {
            readonly data?: components["schemas"]["SchoolClassResponse"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseSchoolProfileResponse: {
            readonly data?: components["schemas"]["SchoolProfileResponse"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseSchoolResponse: {
            readonly data?: components["schemas"]["SchoolResponse"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseSectionResponse: {
            readonly data?: components["schemas"]["SectionResponse"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseStudentDetail: {
            readonly data?: components["schemas"]["StudentDetail"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseStudentGuardian: {
            readonly data?: components["schemas"]["StudentGuardian"];
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly ApiResponseVoid: {
            readonly data?: unknown;
            readonly error?: components["schemas"]["ApiError"];
            readonly success: boolean;
            /** Format: date-time */
            readonly timestamp: string;
            readonly traceId?: string;
        };
        readonly AuditEventResponse: {
            readonly action: string;
            /** Format: uuid */
            readonly actorId?: string;
            readonly actorName?: string;
            readonly actorRoles: readonly string[];
            readonly changedFields: readonly string[];
            readonly entityId?: string;
            readonly entityType?: string;
            /** Format: uuid */
            readonly id: string;
            readonly ipAddress?: string;
            /** Format: date-time */
            readonly occurredAt: string;
            /** @enum {string} */
            readonly outcome: "SUCCESS" | "FAILURE" | "DENIED";
            /** Format: int32 */
            readonly recordCount?: number;
            readonly traceId?: string;
            readonly userAgent?: string;
        };
        readonly ChangePasswordRequest: {
            readonly currentPassword: string;
            readonly newPassword: string;
        };
        readonly CreateEnrolmentRequest: {
            /** Format: uuid */
            readonly academicSessionId: string;
            readonly rollNumber?: string;
            /** Format: uuid */
            readonly sectionId: string;
        };
        readonly CreateSchoolClassRequest: {
            readonly name: string;
        };
        readonly CreateSchoolRequest: {
            /** @enum {string} */
            readonly board: "CBSE" | "CISCE" | "STATE" | "IB" | "CAIE" | "OTHER";
            readonly city?: string;
            readonly code: string;
            readonly name: string;
            readonly schemaName: string;
            readonly state?: string;
        };
        readonly CreateSectionRequest: {
            readonly name: string;
        };
        readonly CurrentEnrolment: {
            readonly className: string;
            readonly rollNumber?: string;
            readonly sectionName: string;
            readonly sessionName: string;
        };
        readonly Enrolment: {
            readonly active: boolean;
            /** Format: uuid */
            readonly classId?: string;
            readonly className?: string;
            /** Format: date */
            readonly enrolledOn: string;
            /** Format: uuid */
            readonly id: string;
            readonly rollNumber?: string;
            /** Format: uuid */
            readonly sectionId: string;
            readonly sectionName?: string;
            /** Format: uuid */
            readonly sessionId: string;
            readonly sessionName?: string;
        };
        readonly GuardianStudent: {
            readonly admissionNumber: string;
            readonly currentEnrolment?: components["schemas"]["CurrentEnrolment"];
            readonly fullName: string;
            readonly primary: boolean;
            /** @enum {string} */
            readonly relation: "FATHER" | "MOTHER" | "GUARDIAN" | "LOCAL_GUARDIAN" | "OTHER";
            /** Format: uuid */
            readonly studentId: string;
        };
        readonly GuardianSummary: {
            readonly email?: string;
            readonly fullName: string;
            /** Format: uuid */
            readonly id: string;
            /** Format: int64 */
            readonly linkedStudentCount: number;
            readonly occupation?: string;
            readonly phone?: string;
        };
        readonly ImportError: {
            readonly column: string;
            readonly message: string;
            /** Format: int32 */
            readonly row: number;
        };
        readonly ImportReport: {
            /** Format: int32 */
            readonly errorCount: number;
            readonly errors: readonly components["schemas"]["ImportError"][];
            /** Format: int32 */
            readonly imported: number;
            /** Format: int32 */
            readonly totalRows: number;
            /** Format: int32 */
            readonly validRows: number;
        };
        readonly LinkGuardianRequest: {
            /** Format: uuid */
            readonly guardianId: string;
            readonly primary: boolean;
            /** @enum {string} */
            readonly relation: "FATHER" | "MOTHER" | "GUARDIAN" | "LOCAL_GUARDIAN" | "OTHER";
        };
        readonly LoginRequest: {
            readonly password: string;
            readonly remembered?: boolean;
            readonly rememberMe?: boolean;
            readonly schoolCode: string;
            readonly username: string;
        };
        readonly LoginResponse: {
            readonly displayName: string;
            readonly mustChangePassword: boolean;
            readonly permissions: readonly string[];
            readonly school: components["schemas"]["SchoolSummary"];
            /** Format: uuid */
            readonly userId: string;
        };
        readonly MeResponse: {
            readonly navigation: readonly components["schemas"]["NavigationItem"][];
            readonly permissions: readonly string[];
            readonly permissionsVersion: string;
            readonly school: components["schemas"]["SchoolSummary"];
            readonly user: components["schemas"]["MeUser"];
        };
        readonly MeUser: {
            readonly displayName: string;
            /** Format: uuid */
            readonly id: string;
            readonly mustChangePassword: boolean;
        };
        readonly NavigationItem: {
            readonly children: readonly components["schemas"]["NavigationItem"][];
            readonly icon?: string;
            readonly id: string;
            readonly labelKey: string;
            /** Format: int32 */
            readonly order: number;
        };
        readonly Pageable: {
            /** Format: int32 */
            readonly page?: number;
            /** Format: int32 */
            readonly size?: number;
            readonly sort?: readonly string[];
        };
        readonly PageResponseAuditEventResponse: {
            readonly content: readonly components["schemas"]["AuditEventResponse"][];
            /** Format: int32 */
            readonly page: number;
            /** Format: int32 */
            readonly size: number;
            /** Format: int64 */
            readonly totalElements: number;
            /** Format: int32 */
            readonly totalPages: number;
        };
        readonly PageResponseGuardianSummary: {
            readonly content: readonly components["schemas"]["GuardianSummary"][];
            /** Format: int32 */
            readonly page: number;
            /** Format: int32 */
            readonly size: number;
            /** Format: int64 */
            readonly totalElements: number;
            /** Format: int32 */
            readonly totalPages: number;
        };
        readonly PageResponseStudentSummary: {
            readonly content: readonly components["schemas"]["StudentSummary"][];
            /** Format: int32 */
            readonly page: number;
            /** Format: int32 */
            readonly size: number;
            /** Format: int64 */
            readonly totalElements: number;
            /** Format: int32 */
            readonly totalPages: number;
        };
        readonly PermissionDefinition: {
            readonly code: string;
            readonly description: string;
            readonly label: string;
            readonly module: string;
        };
        readonly ReorderSchoolClassesRequest: {
            readonly classIds: readonly string[];
        };
        readonly RoleResponse: {
            readonly code: string;
            readonly description?: string;
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly permissions: readonly string[];
            readonly templateCode?: string;
        };
        readonly SaveAcademicSessionRequest: {
            /** Format: date */
            readonly endsOn: string;
            readonly name: string;
            /** Format: date */
            readonly startsOn: string;
        };
        readonly SaveGuardianRequest: {
            /** Format: email */
            readonly email?: string;
            readonly fullName: string;
            readonly occupation?: string;
            readonly phone?: string;
        };
        readonly SaveStudentRequest: {
            readonly admissionNumber: string;
            /** Format: date */
            readonly admittedOn?: string;
            /** Format: date */
            readonly dateOfBirth: string;
            readonly fullName: string;
            /** @enum {string} */
            readonly gender: "MALE" | "FEMALE" | "OTHER";
            /** @enum {string} */
            readonly status: "ACTIVE" | "INACTIVE" | "TRANSFERRED" | "GRADUATED" | "WITHDRAWN";
        };
        readonly SchoolClassResponse: {
            readonly active: boolean;
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly sections: readonly components["schemas"]["SectionResponse"][];
            /** Format: int32 */
            readonly sequence: number;
        };
        readonly SchoolProfileResponse: {
            readonly addressLine1?: string;
            readonly addressLine2?: string;
            readonly affiliationNumber?: string;
            /** @enum {string} */
            readonly board: "CBSE" | "CISCE" | "STATE" | "IB" | "CAIE" | "OTHER";
            readonly city?: string;
            readonly code: string;
            readonly configured: boolean;
            readonly email?: string;
            readonly name: string;
            readonly phone?: string;
            readonly pincode?: string;
            readonly principalName?: string;
            readonly schemaName: string;
            readonly state?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
            readonly website?: string;
        };
        readonly SchoolResponse: {
            readonly active: boolean;
            /** @enum {string} */
            readonly board: "CBSE" | "CISCE" | "STATE" | "IB" | "CAIE" | "OTHER";
            readonly city?: string;
            readonly code: string;
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly schemaName: string;
            readonly state?: string;
        };
        readonly SchoolSummary: {
            readonly code: string;
            readonly name: string;
        };
        readonly SectionResponse: {
            readonly active: boolean;
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
        };
        readonly StudentDetail: {
            readonly admissionNumber: string;
            /** Format: date */
            readonly admittedOn?: string;
            readonly currentEnrolment?: components["schemas"]["CurrentEnrolment"];
            /** Format: date */
            readonly dateOfBirth: string;
            readonly enrolments: readonly components["schemas"]["Enrolment"][];
            readonly fullName: string;
            /** @enum {string} */
            readonly gender: "MALE" | "FEMALE" | "OTHER";
            readonly guardians: readonly components["schemas"]["StudentGuardian"][];
            /** Format: uuid */
            readonly id: string;
            /** @enum {string} */
            readonly status: "ACTIVE" | "INACTIVE" | "TRANSFERRED" | "GRADUATED" | "WITHDRAWN";
        };
        readonly StudentGuardian: {
            readonly email?: string;
            readonly fullName: string;
            /** Format: uuid */
            readonly guardianId: string;
            /** Format: uuid */
            readonly linkId: string;
            readonly occupation?: string;
            readonly phone?: string;
            readonly primary: boolean;
            /** @enum {string} */
            readonly relation: "FATHER" | "MOTHER" | "GUARDIAN" | "LOCAL_GUARDIAN" | "OTHER";
        };
        readonly StudentSummary: {
            readonly admissionNumber: string;
            readonly currentEnrolment?: components["schemas"]["CurrentEnrolment"];
            readonly fullName: string;
            /** @enum {string} */
            readonly gender: "MALE" | "FEMALE" | "OTHER";
            /** Format: uuid */
            readonly id: string;
            /** @enum {string} */
            readonly status: "ACTIVE" | "INACTIVE" | "TRANSFERRED" | "GRADUATED" | "WITHDRAWN";
        };
        readonly UpdateEnrolmentRequest: {
            readonly active: boolean;
            readonly rollNumber?: string;
            /** Format: uuid */
            readonly sectionId: string;
        };
        readonly UpdateSchoolClassRequest: {
            readonly active: boolean;
            readonly name: string;
        };
        readonly UpdateSchoolProfileRequest: {
            readonly addressLine1: string;
            readonly addressLine2?: string;
            readonly affiliationNumber?: string;
            /** @enum {string} */
            readonly board: "CBSE" | "CISCE" | "STATE" | "IB" | "CAIE" | "OTHER";
            readonly city: string;
            readonly code?: string;
            /** Format: email */
            readonly email: string;
            readonly name: string;
            readonly phone: string;
            readonly pincode: string;
            readonly principalName: string;
            readonly schemaName?: string;
            readonly state: string;
            readonly website?: string;
        };
        readonly UpdateSectionRequest: {
            readonly active: boolean;
            readonly name: string;
        };
        readonly UpdateStudentGuardianRequest: {
            readonly primary: boolean;
            /** @enum {string} */
            readonly relation: "FATHER" | "MOTHER" | "GUARDIAN" | "LOCAL_GUARDIAN" | "OTHER";
        };
        readonly UserSummary: {
            readonly displayName: string;
            /** Format: uuid */
            readonly id: string;
            readonly status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly list_4: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseListSchoolClassResponse"];
                };
            };
        };
    };
    readonly create_4: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateSchoolClassRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseSchoolClassResponse"];
                };
            };
        };
    };
    readonly update_5: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UpdateSchoolClassRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseSchoolClassResponse"];
                };
            };
        };
    };
    readonly addSection: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateSectionRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseSectionResponse"];
                };
            };
        };
    };
    readonly reorder: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ReorderSchoolClassesRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseListSchoolClassResponse"];
                };
            };
        };
    };
    readonly updateSection: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UpdateSectionRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseSectionResponse"];
                };
            };
        };
    };
    readonly list_3: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseListAcademicSessionResponse"];
                };
            };
        };
    };
    readonly create_3: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SaveAcademicSessionRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseAcademicSessionResponse"];
                };
            };
        };
    };
    readonly update_4: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SaveAcademicSessionRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseAcademicSessionResponse"];
                };
            };
        };
    };
    readonly makeCurrent: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseListAcademicSessionResponse"];
                };
            };
        };
    };
    readonly permissions: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseListPermissionDefinition"];
                };
            };
        };
    };
    readonly roles: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseListRoleResponse"];
                };
            };
        };
    };
    readonly users: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseListUserSummary"];
                };
            };
        };
    };
    readonly search: {
        readonly parameters: {
            readonly query: {
                readonly action?: string;
                readonly actorId?: string;
                readonly from?: string;
                readonly pageable: components["schemas"]["Pageable"];
                readonly to?: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponsePageResponseAuditEventResponse"];
                };
            };
        };
    };
    readonly login: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LoginRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseLoginResponse"];
                };
            };
        };
    };
    readonly logout: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    readonly changePassword: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    readonly list_2: {
        readonly parameters: {
            readonly query: {
                readonly pageable: components["schemas"]["Pageable"];
                readonly q?: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponsePageResponseGuardianSummary"];
                };
            };
        };
    };
    readonly create_2: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SaveGuardianRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseGuardianSummary"];
                };
            };
        };
    };
    readonly update_3: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SaveGuardianRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseGuardianSummary"];
                };
            };
        };
    };
    readonly students: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseListGuardianStudent"];
                };
            };
        };
    };
    readonly me: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseMeResponse"];
                };
            };
        };
    };
    readonly profile: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseSchoolProfileResponse"];
                };
            };
        };
    };
    readonly update_2: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UpdateSchoolProfileRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseSchoolProfileResponse"];
                };
            };
        };
    };
    readonly list_1: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseListSchoolResponse"];
                };
            };
        };
    };
    readonly create_1: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateSchoolRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseSchoolResponse"];
                };
            };
        };
    };
    readonly get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseSchoolResponse"];
                };
            };
        };
    };
    readonly list: {
        readonly parameters: {
            readonly query: {
                readonly pageable: components["schemas"]["Pageable"];
                readonly q?: string;
                readonly sectionId?: string;
                readonly status?: "ACTIVE" | "INACTIVE" | "TRANSFERRED" | "GRADUATED" | "WITHDRAWN";
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponsePageResponseStudentSummary"];
                };
            };
        };
    };
    readonly create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SaveStudentRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseStudentDetail"];
                };
            };
        };
    };
    readonly find: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseStudentDetail"];
                };
            };
        };
    };
    readonly update_1: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SaveStudentRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseStudentDetail"];
                };
            };
        };
    };
    readonly enrol: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateEnrolmentRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseEnrolment"];
                };
            };
        };
    };
    readonly updateEnrolment: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly enrolmentId: string;
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UpdateEnrolmentRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseEnrolment"];
                };
            };
        };
    };
    readonly link: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly studentId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LinkGuardianRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseStudentGuardian"];
                };
            };
        };
    };
    readonly update: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly linkId: string;
                readonly studentId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UpdateStudentGuardianRequest"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseStudentGuardian"];
                };
            };
        };
    };
    readonly unlink: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly linkId: string;
                readonly studentId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly importStudents: {
        readonly parameters: {
            readonly query: {
                readonly academicSessionId: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "multipart/form-data": {
                    /** Format: binary */
                    readonly file: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseImportReport"];
                };
            };
        };
    };
    readonly validate: {
        readonly parameters: {
            readonly query: {
                readonly academicSessionId: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "multipart/form-data": {
                    /** Format: binary */
                    readonly file: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["ApiResponseImportReport"];
                };
            };
        };
    };
}
